name: qpsolvers
channels:
    - conda-forge
dependencies:
    - cmake
    - proxsuite
    - qpsolvers
    - pip >=21.3.1
    - pip:
        - daqp
        - furo >= 2023.8.17
        - highspy
        - piqp >= 0.2.2
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-mathjax-offline
